python2 ../src/epiGBS/RnBeads/rnbeads_analysis.py add_and_analysis \
-f ./output_DMP_test_data/ref.fa \
-b ./output_DMP_test_data/methylation.filtered.bed \
-sf ./output_DMP_test_data/samples.csv \
-tmp /tmp \
-s duckweed \
-g nioo \
-v 0.1 \
-ac stella \
-mr 3 \
--context CHH
